services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - db

  db:
    image: postgres:latest  # Placeholder image, not used for SQLite
    environment:
      POSTGRES_DB: shoerackorginals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: albert